
--------------------------------------------------------------
-- Database creation Script

-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.

-- Entity Model :Entity Relationship Diagram

-- To drop the tables generated by this script run -
--   'PRCS_drop_tables.sql'

--------------------------------------------------------------
-- All tables have been prefixed with pl for easy identification

set echo on;
--------------------------------------------------------------
-- Table Creation --

-- Create a Database table to represent the "reported_crime" entity.
CREATE TABLE pl_reported_crime(
	reported_crime_id	INTEGER NOT NULL,
	date_reported	DATE NOT NULL,
	crime_postcode	VARCHAR(16) NOT NULL,
	crime_status	VARCHAR(16) NOT NULL,
	date_closed 	VARCHAR(20),
	fk1_crime_type_id	INTEGER NOT NULL,
	fk2_station_id	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "reported_crime".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_reported_crime PRIMARY KEY (reported_crime_id)
);

-- Create a Database table to represent the "pl_witness" entity.
CREATE TABLE pl_witness(
	witness_id	INTEGER NOT NULL,
	witness_name	VARCHAR(30) NOT NULL,
	witness_address	VARCHAR(100), 
        witness_type_id	INTEGER NOT NULL
		);

-- Create a Database table to represent the "pl_witness_type" entity.
CREATE TABLE pl_witness_type(
	witness_type_id	INTEGER NOT NULL,
	witness_type_desc	VARCHAR(50),
	-- Specify the PRIMARY KEY constraint for table "pl_witness_type".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_witness_type PRIMARY KEY (witness_type_id)
);

-- Create a Database table to represent the "crime_type" entity.
CREATE TABLE pl_crime_type(
	crime_type_id	INTEGER NOT NULL,
	crime_type_desc	VARCHAR(50) NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "pl_crime_type".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_crime_type PRIMARY KEY (crime_type_id)
);

-- Create a Database table to represent the "pl_police_employee" entity.
CREATE TABLE pl_police_employee(
	emp_id	INTEGER NOT NULL,
	emp_name	VARCHAR(30) NOT NULL,
	emp_grade	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "pl_police_employee".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_police_emp PRIMARY KEY (emp_id)
);

-- Create a Database table to represent the "pl_station" entity.
CREATE TABLE pl_station(
	station_id	INTEGER NOT NULL,
	station_name	VARCHAR(30) NOT NULL,
	fk1_area_id	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "pl_station".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_station PRIMARY KEY (station_id)
);

-- Create a Database table to represent the "pl_area" entity.
CREATE TABLE pl_area(
	area_id	INTEGER NOT NULL,
	area_name	VARCHAR(30) NOT NULL UNIQUE,
	parent_area	INTEGER CONSTRAINT fk_area_to_area REFERENCES pl_area,
	-- Specify the PRIMARY KEY constraint for table "area".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_area PRIMARY KEY (area_id)
);


--------------------------------------------------------------
-- Create LINK tables --

-- These tables do not appear as entities on the model. The reason they are created
-- is to allow certain types of relationships to be implemented in a Relational type Database.
-- Each link table tends to represent a specific relationship that appears on the model.
-- The attributes contained in link tables are identified from the entities at either side
-- of the relationship. i.e. they do not define attributes in their own right.
-- Indeed foreign key constraints are always created to ensure referential integrity between the
-- link table attributes and the primary key attributes on which they are based.

-- Create a link table to represent the "is_associated_with" relationship.
-- The attributes of this table are taken from the primary keys of table "pl_reported_crime" and
-- table "pl_witness", i.e. each end of the relationship. A link table was created
-- because "is_associated_with" is a many to many relationship which required resolving.
-- notice how the primary key is a combination of the keys from both related tables (pl_reported_crime and pl_witness).

-- JC renamed this table statement and added attributes
CREATE TABLE pl_statement(
	s_reported_crime_id	INTEGER NOT NULL,
	d_witness_id	INTEGER NOT NULL,
	statement_type  VARCHAR (30) NOT NULL,
	statement_location VARCHAR (50) NOT NULL,
	PRIMARY KEY (s_reported_crime_id,d_witness_id),
	FOREIGN KEY(s_reported_crime_id) REFERENCES pl_reported_crime(reported_crime_id));

-- JC Physical db design decision not to include this table
--
-- Create a link table to represent the "is_contained_in" relationship.
-- The attributes of this table are taken from the primary keys of table "pl_area" and
-- table "pl_area", i.e. each end of the relationship. A link table was created
-- because "is_contained_in" is a one to many relationship with optionality at the one side.
-- notice how the primary key is only based on the key of the table at the many side, i.e. table "pl_area".
--CREATE TABLE pl_area_in_area(
--	s_area_id	INTEGER NOT NULL,
--	d_area_id	INTEGER NOT NULL,
--	PRIMARY KEY (d_area_id),
--	FOREIGN KEY(s_area_id) REFERENCES pl_area(area_id),
--	FOREIGN KEY(d_area_id) REFERENCES pl_area(area_id) 
--);

-- JC renamed this table as pl_work_allocation
-- Create a link table to represent the "is_investigated_by" relationship.
-- The attributes of this table are taken from the primary keys of table "pl_reported_crime" and
-- table "pl_police_employee", i.e. each end of the relationship. A link table was created
-- because "is_investigated_by" is a many to many relationship which required resolving.
-- notice how the primary key is a combination of the keys from both related tables -- (pl_reported_crime and pl_police_employee).
CREATE TABLE pl_work_allocation(
	s_reported_crime_id	INTEGER NOT NULL,
	d_emp_id		INTEGER NOT NULL,
	work_desc		VARCHAR(50) NOT NULL,
	lead_police_officer 	INTEGER NOT NULL,
	work_start_date		DATE NOT NULL,
	work_end_date		DATE NOT NULL,
	PRIMARY KEY (s_reported_crime_id,d_emp_id),
	FOREIGN KEY(s_reported_crime_id) REFERENCES 	pl_reported_crime(reported_crime_id),
	FOREIGN KEY(d_emp_id) REFERENCES pl_police_employee(emp_id));


--------------------------------------------------------------
-- Alter Tables to add fk constraints --

-- Now all the tables have been created the ALTER TABLE command is used to define some additional
-- constraints.  These typically constrain values of foreign keys to be associated in some way
-- with the primary keys of related tables.  Foreign key constraints can actually be specified
-- when each table is created, but doing so can lead to dependency problems within the script
-- i.e. tables may be referenced before they have been created.  This method is therefore safer.

-- Alter table to add new constraints required to implement the "contains" relationship

-- This constraint ensures that the foreign key of table "pl_station"
-- correctly references the primary key of table "pl_area"

ALTER TABLE pl_station ADD CONSTRAINT fk1_station_to_area FOREIGN KEY(fk1_area_id) REFERENCES pl_area(area_id);

-- Alter table to add new constraints required to implement the "is_of" relationship

-- This constraint ensures that the foreign key of table "pl_reported_crime"
-- correctly references the primary key of table "pl_crime_type"

ALTER TABLE pl_reported_crime ADD CONSTRAINT fk1_rc_to_ctype FOREIGN KEY(fk1_crime_type_id) REFERENCES pl_crime_type(crime_type_id);

-- Alter table to add new constraints required to implement the "is_assigned_to" relationship

-- This constraint ensures that the foreign key of table "pl_reported_crime"
-- correctly references the primary key of table "pl_station"

ALTER TABLE pl_reported_crime ADD CONSTRAINT fk2_reported_crime_to_station FOREIGN KEY(fk2_station_id) REFERENCES pl_station(station_id);

--------------------------------------------------------------
-- End of DDL file auto-generation
--------------------------------------------------------------
