
--------------------------------------------------------------
-- Database creation Script

-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.

-- Verbose generation: ON

-- note: spaces within table/column names have been replaced by underscores (_)

-- Target DB: SQL2

-- Entity Model :Entity Relationship Diagram

-- To drop the tables generated by this script run -
--   'C:\Users\user\Desktop\data mart (SS)_drop.sql'

--------------------------------------------------------------



--------------------------------------------------------------
-- Table Creation --

-- Each entity on the model is represented by a table that needs to be created within the Database.
-- Within SQL new tables are created using the CREATE TABLE command.
-- When a table is created its name and its attributes are defined.
-- The values of which are derived from those specified on the model.
-- Certain constraints are sometimes also specified, such as identification of primary keys.

-- Create a Database table to represent the "CRIME_REPORT_FACT" entity.
CREATE TABLE CRIME_REPORT_FACT(
	CRIME_REPORT_ID	INTEGER NOT NULL,
	STATION_ID	INTEGER NOT NULL,
	CATEGORY_ID	INTEGER NOT NULL,
	OFFICER_ID	INTEGER NOT NULL,
	REPORTED_TIME_ID	INTEGER NOT NULL,
	CLOSED_TIME_ID	INTEGER,
	CRIME_STATUS	INTEGER,
	RESOLUTION_DUATION	INTEGER,
	fk1_STATION_ID	INTEGER NOT NULL,
	fk2_CATEGORY_ID	INTEGER NOT NULL,
	fk3_TIME_ID	INTEGER NOT NULL,
	fk4_OFFICER_ID	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "CRIME_REPORT_FACT".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_CRIME_REPORT_FACT PRIMARY KEY (CRIME_REPORT_ID)
);

-- Create a Database table to represent the "REGIONAL_STATION_DIM" entity.
CREATE TABLE REGIONAL_STATION_DIM(
	STATION_ID	INTEGER NOT NULL,
	STATION_NAME	VARCHAR(20),
	CITY_NAME	VARCHAR(20),
	POSTCODE	VARCHAR(10),
	-- Specify the PRIMARY KEY constraint for table "REGIONAL_STATION_DIM".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_REGIONAL_STATION_DIM PRIMARY KEY (STATION_ID)
);

-- Create a Database table to represent the "TIME_DIM" entity.
CREATE TABLE TIME_DIM(
	TIME_ID	INTEGER NOT NULL,
	FULL_DATE	TIMESTAMP(8),
	DAY	TIMESTAMP(8),
	MONTH	TIMESTAMP(8),
	YEAR	TIMESTAMP(8),
	QUARTER	TIMESTAMP(8),
	-- Specify the PRIMARY KEY constraint for table "TIME_DIM".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_TIME_DIM PRIMARY KEY (TIME_ID)
);

-- Create a Database table to represent the "CRIME_CATEGORY_DIM" entity.
CREATE TABLE CRIME_CATEGORY_DIM(
	CATEGORY_ID	INTEGER NOT NULL,
	CRIME_GROUP	VARCHAR(20),
	CATEGORY_DESCRIPTION	VARCHAR(20),
	-- Specify the PRIMARY KEY constraint for table "CRIME_CATEGORY_DIM".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_CRIME_CATEGORY_DIM PRIMARY KEY (CATEGORY_ID)
);

-- Create a Database table to represent the "OFFICER_DIM" entity.
CREATE TABLE OFFICER_DIM(
	OFFICER_ID	INTEGER NOT NULL,
	OFFICER_NAME	VARCHAR(20),
	RANK	INTEGER,
	DEPARTMENT	VARCHAR(20),
	-- Specify the PRIMARY KEY constraint for table "OFFICER_DIM".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_OFFICER_DIM PRIMARY KEY (OFFICER_ID)
);


--------------------------------------------------------------
-- Alter Tables to add fk constraints --

-- Now all the tables have been created the ALTER TABLE command is used to define some additional
-- constraints.  These typically constrain values of foreign keys to be associated in some way
-- with the primary keys of related tables.  Foreign key constraints can actually be specified
-- when each table is created, but doing so can lead to dependency problems within the script
-- i.e. tables may be referenced before they have been created.  This method is therefore safer.

-- Alter table to add new constraints required to implement the "CRIME_REPORT_FACT_REGIONAL_STATION_DIM" relationship

-- This constraint ensures that the foreign key of table "CRIME_REPORT_FACT"
-- correctly references the primary key of table "REGIONAL_STATION_DIM"

ALTER TABLE CRIME_REPORT_FACT ADD CONSTRAINT fk1_CRIME_REPORT_FACT_to_REGIONAL_STATION_DIM FOREIGN KEY(fk1_STATION_ID) REFERENCES REGIONAL_STATION_DIM(STATION_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "CRIME_REPORT_FACT_CRIME_CATEGORY_DIM" relationship

-- This constraint ensures that the foreign key of table "CRIME_REPORT_FACT"
-- correctly references the primary key of table "CRIME_CATEGORY_DIM"

ALTER TABLE CRIME_REPORT_FACT ADD CONSTRAINT fk2_CRIME_REPORT_FACT_to_CRIME_CATEGORY_DIM FOREIGN KEY(fk2_CATEGORY_ID) REFERENCES CRIME_CATEGORY_DIM(CATEGORY_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "CRIME_REPORT_FACT_TIME_DIM" relationship

-- This constraint ensures that the foreign key of table "CRIME_REPORT_FACT"
-- correctly references the primary key of table "TIME_DIM"

ALTER TABLE CRIME_REPORT_FACT ADD CONSTRAINT fk3_CRIME_REPORT_FACT_to_TIME_DIM FOREIGN KEY(fk3_TIME_ID) REFERENCES TIME_DIM(TIME_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "CRIME_REPORT_FACT_OFFICER_DIM" relationship

-- This constraint ensures that the foreign key of table "CRIME_REPORT_FACT"
-- correctly references the primary key of table "OFFICER_DIM"

ALTER TABLE CRIME_REPORT_FACT ADD CONSTRAINT fk4_CRIME_REPORT_FACT_to_OFFICER_DIM FOREIGN KEY(fk4_OFFICER_ID) REFERENCES OFFICER_DIM(OFFICER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;


--------------------------------------------------------------
-- End of DDL file auto-generation
--------------------------------------------------------------
