-- Drop tables --
DROP TABLE CRIME_REPORT_FACT;
DROP TABLE REGIONAL_STATION_DIM;
DROP TABLE TIME_DIM;
DROP TABLE CRIME_CATEGORY_DIM;
DROP TABLE OFFICER_DIM;

-- creating the fact table
CREATE TABLE CRIME_REPORT_FACT(
	CRIME_REPORT_ID	INTEGER NOT NULL ,          -- primary key for the fact table
	STATION_ID	INTEGER NOT NULL,               -- fk already present here
	CATEGORY_ID	INTEGER NOT NULL,               -- fk already present here
	OFFICER_ID	INTEGER NOT NULL,               -- fk already present here
	REPORTED_TIME_ID	INTEGER NOT NULL,       -- fk already present here
	CLOSED_TIME_ID	INTEGER,                    -- fk already present here
	CRIME_STATUS	INTEGER, -- metric
	RESOLUTION_DUATION	INTEGER, -- metric
	-- fk1_STATION_ID	INTEGER NOT NULL,           not needed as the fk is already present
	-- fk2_CATEGORY_ID	INTEGER NOT NULL,           not needed as the fk is already present
	-- fk3_TIME_ID	INTEGER NOT NULL,               not needed as the fk is already present
	-- fk4_OFFICER_ID	INTEGER NOT NULL,           not needed as the fk is already present
	CONSTRAINT	pk_CRIME_REPORT_FACT PRIMARY KEY (CRIME_REPORT_ID)
);

-- Create a Database table to represent the "REGIONAL_STATION_DIM" entity.
CREATE TABLE REGIONAL_STATION_DIM(
	STATION_ID	INTEGER NOT NULL,
	STATION_NAME	VARCHAR(20),
	CITY_NAME	VARCHAR(20),
	POSTCODE	VARCHAR(10),
	CONSTRAINT	pk_REGIONAL_STATION_DIM PRIMARY KEY (STATION_ID)
);

-- Create a Database table to represent the "TIME_DIM" entity.
CREATE TABLE TIME_DIM(
	TIME_ID	INTEGER NOT NULL,
	FULL_DATE	TIMESTAMP(8),
	DAY	TIMESTAMP(8),
	MONTH	TIMESTAMP(8),
	YEAR	TIMESTAMP(8),
	QUARTER	TIMESTAMP(8),
	CONSTRAINT	pk_TIME_DIM PRIMARY KEY (TIME_ID)
);

-- Create a Database table to represent the "CRIME_CATEGORY_DIM" entity.
CREATE TABLE CRIME_CATEGORY_DIM(
	CATEGORY_ID	INTEGER NOT NULL,
	CRIME_GROUP	VARCHAR(20),
	CATEGORY_DESCRIPTION	VARCHAR(20),
	CONSTRAINT	pk_CRIME_CATEGORY_DIM PRIMARY KEY (CATEGORY_ID)
);

-- Create a Database table to represent the "OFFICER_DIM" entity.
CREATE TABLE OFFICER_DIM(
	OFFICER_ID	INTEGER NOT NULL,
	OFFICER_NAME	VARCHAR(20),
	RANK	INTEGER,
	DEPARTMENT	VARCHAR(20),
	CONSTRAINT	pk_OFFICER_DIM PRIMARY KEY (OFFICER_ID)
);

--    ON DELETE CASCADE; not placing this cause we do not delete data from the data warehouse

--  "CRIME_REPORT_FACT" relationship
ALTER TABLE CRIME_REPORT_FACT 
ADD CONSTRAINT fk1_CRIME_REPORT_FACT_to_REGIONAL_STATION_DIM 
FOREIGN KEY(STATION_ID) 
REFERENCES REGIONAL_STATION_DIM(STATION_ID);

-- "CRIME_REPORT_FACT_CRIME_CATEGORY_DIM" relationship
ALTER TABLE CRIME_REPORT_FACT 
ADD CONSTRAINT fk2_CRIME_REPORT_FACT_to_CRIME_CATEGORY_DIM 
FOREIGN KEY(CATEGORY_ID) 
REFERENCES CRIME_CATEGORY_DIM(CATEGORY_ID);

--  "CRIME_REPORT_FACT_TIME_DIM" relationship
ALTER TABLE CRIME_REPORT_FACT 
ADD CONSTRAINT fk3_CRIME_REPORT_FACT_to_TIME_DIM 
FOREIGN KEY(REPORTED_TIME_ID) 
REFERENCES TIME_DIM(TIME_ID);

--  "CRIME_REPORT_FACT_TIME_DIM" relationship
ALTER TABLE CRIME_REPORT_FACT 
ADD CONSTRAINT fk4_CRIME_REPORT_FACT_to_TIME_DIM 
FOREIGN KEY(CLOSED_TIME_ID) 
REFERENCES TIME_DIM(TIME_ID);

-- "CRIME_REPORT_FACT_OFFICER_DIM" relationship
ALTER TABLE CRIME_REPORT_FACT 
ADD CONSTRAINT fk5_CRIME_REPORT_FACT_to_OFFICER_DIM 
FOREIGN KEY(OFFICER_ID) 
REFERENCES OFFICER_DIM(OFFICER_ID);